# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 08:54
from __future__ import unicode_literals

from django.db import migrations
import pybb.util
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0006_auto_20160722_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=pybb.util.FilePathGenerator(to=b'pybb/avatar'), verbose_name='Avatar'),
        ),
    ]
